Repository spenserblack/gengo, pull requests merged in 2023-10, with the labels that each got.

#213 Add support for Windows Batch files
  gengo/languages.yaml
Labels: new-language

#214 Add Arduino language
  gengo/languages.yaml
Labels: new-language

#210 Parallelize fetching file contents
  Cargo.lock
  Cargo.toml
  gengo-bin/Cargo.toml
  gengo/src/file_source/git.rs
  gengo/src/file_source/mod.rs
  gengo/src/lib.rs
  gengo/tests/gengo_test.rs
  gengo/tests/snapshots/gengo_test__javascript.snap
Labels: semver-major

#217 Sort CLI output by size *and* name
  gengo-bin/src/cli.rs
Labels: semver-patch

#218 Use shared state to reduce expensive clones
  gengo/src/file_source/git.rs
  gengo/src/file_source/mod.rs
  gengo/src/lib.rs
Labels: semver-major

#220 Add `samples-test` test crate
  .gitattributes
  Cargo.lock
  Cargo.toml
  docs/HACKING.md
  samples-test/Cargo.toml
  samples-test/samples/Ruby/repofetch.rb
  samples-test/src/lib.rs
Labels: ignore-for-release

#222 Support Swift
  gengo/languages.yaml
Labels: new-language, hacktoberfest-accepted

#229 Increase `gix` version range
  Cargo.lock
  gengo/Cargo.toml
Labels: dependencies, rust

#231 Install/cache tarpaulin manually
  .github/workflows/ci.yml
Labels: ignore-for-release

#234 Support GDScript
  gengo/languages.yaml
Labels: new-language
