Repository spenserblack/gengo, pull requests merged in 2023-09, with the labels that each got.

#97 Dockerize
  .dockerignore
  .editorconfig
  .github/workflows/release.yml
  Dockerfile
  README.md
Labels: help wanted

#186 Improve documentation detection
  gengo/src/documentation.rs
Labels: semver-patch

#192 add Odin support
  gengo/languages.yaml
Labels: new-language

#191 Change `Gengo` to take a generic `FileSource`
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  gengo-bin/Cargo.toml
  gengo-bin/src/cli.rs
  gengo/Cargo.toml
  gengo/benches/run_on_self.rs
  gengo/src/analysis/mod.rs
  gengo/src/builder.rs
  gengo/src/file_source/git.rs
  gengo/src/file_source/mod.rs
  gengo/src/lib.rs
  gengo/tests/gengo_test.rs
  gengo/tests/snapshots/gengo_test__javascript.snap
Labels: semver-major

#194 Make `Builder` take a `FileSource`
  gengo-bin/src/cli.rs
  gengo/benches/run_on_self.rs
  gengo/src/builder.rs
  gengo/src/lib.rs
  gengo/tests/gengo_test.rs
Labels: semver-major
